# -*- coding: utf-8 -*-
from . import vm_traits
from . import vm_wizard
from . import hypervisor_server
from . import hypervisor_resources
from . import product_attribute
from . import vm_template
from . import product_template
from . import vm_rental_machine
from . import sale_order
from . import vm_snapshot
from . import vm_audit_log
from . import vm_config_backup
from . import res_config_settings
from . import vm_pricing
from . import vm_pricing_extensions
from . import vm_user_management
from . import vm_user_manager
from . import res_users
